name: Build Github Pages
on:
  workflow_dispatch
jobs:
  buildpacks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: RbCaVi/lua-factorio-data
          path: lua-factorio-data
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.2.4"
      - name: List lua
        run: find .lua
      - name: Echo path
        run: echo "$PATH"
      - name: Which lua
        run: which lua
      - name: Lua version
        run: lua -v
      - name: Cache factorio
        uses: actions/cache@v4
        with:
          path: factorio
          key: factorio
      - name: Get mods
        run: bash getmods.sh
      - name: Move mods
        run: bash copymods.sh
      - name: Show files
        run: find ./assets/
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./assets/

  # Deployment job
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: buildpacks
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
